// src/data.js
export const initialMembers = [
    {
        id: "1",
        name: "Nguyen Van A",
        avatar: "/default-avatar.jpg",
        title: "Frontend Developer",
        description: "Passionate about creating user-friendly interfaces",
        email: "nguyen.a@example.com",
        phone: "+84 123 456 789",
        skills: ["React", "JavaScript", "CSS"],
        experience: "3 years at Tech Corp",
        education: "BSc Computer Science, Hanoi University",
        projects: ["E-commerce Platform", "Portfolio Website"],
    },
    {
        id: "2",
        name: "Tran Thi B",
        avatar: "/default-avatar.jpg",
        title: "Backend Developer",
        description: "Expert in building scalable APIs",
        email: "tran.b@example.com",
        phone: "+84 987 654 321",
        skills: ["Node.js", "Express", "MongoDB"],
        experience: "4 years at Data Solutions",
        education: "MSc Computer Science, HCMC University",
        projects: ["API Gateway", "Inventory System"],
    },
    {
        id: "3",
        name: "Le Van C",
        avatar: "/default-avatar.jpg",
        title: "UI/UX Designer",
        description: "Creating intuitive user experiences",
        email: "le.c@example.com",
        phone: "+84 456 789 123",
        skills: ["Figma", "Adobe XD", "Prototyping"],
        experience: "2 years at Design Studio",
        education: "BA Graphic Design, FPT University",
        projects: ["Mobile App UI", "Website Redesign"],
    },
    {
        id: "4",
        name: "Pham Thi D",
        avatar: "/default-avatar.jpg",
        title: "Full Stack Developer",
        description: "Building end-to-end web solutions",
        email: "pham.d@example.com",
        phone: "+84 321 654 987",
        skills: ["React", "Node.js", "SQL"],
        experience: "5 years at Web Corp",
        education: "BSc Software Engineering, VNU",
        projects: ["CRM System", "E-learning Platform"],
    },
];