// src/data.js
export const initialMembers = [
    {
        id: "1",
        name: "Huỳnh Phong Đạt",
        avatar: "/default-avatar.jpg",
        title: "Lập trình viên Frontend",
        description: "Đam mê tạo giao diện thân thiện với người dùng",
        email: "nguyen.a@example.com",
        phone: "+84 123 456 789",
        skills: ["React", "JavaScript", "CSS"],
        experience: "3 năm tại Tech Corp",
        education: "Cử nhân Khoa học Máy tính, ĐH Hà Nội",
        projects: ["Nền tảng Thương mại Điện tử", "Website Portfolio"],
    },
    {
        id: "2",
        name: "Trần Thị B",
        avatar: "/default-avatar.jpg",
        title: "Lập trình viên Backend",
        description: "Chuyên gia xây dựng API có khả năng mở rộng",
        email: "tran.b@example.com",
        phone: "+84 987 654 321",
        skills: ["Node.js", "Express", "MongoDB"],
        experience: "4 năm tại Data Solutions",
        education: "Thạc sĩ Khoa học Máy tính, ĐH TP.HCM",
        projects: ["API Gateway", "Hệ thống Quản lý Kho"],
    },
    {
        id: "3",
        name: "Lê Văn C",
        avatar: "/default-avatar.jpg",
        title: "Nhà thiết kế UI/UX",
        description: "Tạo trải nghiệm người dùng trực quan",
        email: "le.c@example.com",
        phone: "+84 456 789 123",
        skills: ["Figma", "Adobe XD", "Tạo mẫu"],
        experience: "2 năm tại Design Studio",
        education: "Cử nhân Thiết kế Đồ họa, ĐH FPT",
        projects: ["Giao diện Ứng dụng Di động", "Tái thiết kế Website"],
    },
    {
        id: "4",
        name: "Phạm Thị D",
        avatar: "/default-avatar.jpg",
        title: "Lập trình viên Full Stack",
        description: "Xây dựng giải pháp web toàn diện",
        email: "pham.d@example.com",
        phone: "+84 321 654 987",
        skills: ["React", "Node.js", "SQL"],
        experience: "5 năm tại Web Corp",
        education: "Cử nhân Kỹ thuật Phần mềm, ĐH Quốc gia",
        projects: ["Hệ thống CRM", "Nền tảng E-learning"],
    },
];